# Generated by Django 3.1.4 on 2021-09-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('father_name', models.CharField(max_length=50)),
                ('birth_year', models.IntegerField()),
                ('primary_phone', models.CharField(max_length=13)),
                ('is_whatsapp', models.BooleanField()),
                ('whatsapp_number', models.CharField(max_length=13)),
                ('hs_year', models.IntegerField()),
                ('enroll_year', models.IntegerField()),
                ('stream', models.IntegerField()),
                ('current_profession', models.CharField(max_length=50)),
                ('reserved_string', models.CharField(max_length=50)),
            ],
        ),
    ]
